version: "2"

volumes:
  spongeauth-db:

services:
  db:
    image: postgres:9.6
    volumes:
      - spongeauth-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: spongeauth
      POSTGRES_PASSWORD: spongeauth
      POSTGRES_DB: spongeauth
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
  redis:
    image: redis:6.0.6
    command: redis-server --requirepass changeme
  app:
    build: .
    ports:
      - "8000:8000"
    links:
      - "db"
      - "mail"
      - "redis"
    environment:
      EMAIL_HOST_USER: email@username.com
      EMAIL_HOST_PASSWORD: "PasswordForEmail"
      EMAIL_HOST: smtp.for.email.com
      EMAIL_HOST_PORT: 587
      SECRET: changeme
      SECRET_KEY: changeme
      DB_NAME: spongeauth
      DB_USER: spongeauth
      DB_PASSWORD: spongeauth
      DB_HOST: db
      DJANGO_SETTINGS_MODULE: spongeauth.settings.prod
      DJANGO_SETTINGS_SKIP_LOCAL: "True"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: changeme
      REDIS_DEFAULT_TIMEOUT: 300
      DEBUG: "True"
    volumes:
      - .:/app
