version: "2"

volumes:
  spongeauth-db:

services:
  db:
    image: postgres:9.6
    volumes:
      - spongeauth-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: spongeauth
      POSTGRES_PASSWORD: spongeauth
      POSTGRES_DB: spongeauth
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
  app:
    build: .
    ports:
      - "8000:8000"
    links:
      - "db"
      - "mail"
    environment:
      EMAIL_HOST: oremail.powernukkit.org
      EMAIL_HOST_PORT: 587
      EMAIL_HOST_USER: changeme@powernukkit.org
      EMAIL_HOST_PASSWORD: changeme
    volumes:
      - .:/app
