# Generated by Django 2.1.5 on 2019-02-13 14:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0012_auto_20190102_1545")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_tag",
            field=models.CharField(
                blank=True, max_length=255, validators=[accounts.models.validate_discord_tag], verbose_name="Discord Tag"
            ),
        )
    ]
